# Generated by Django 3.2.4 on 2021-07-15 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_styles', models.CharField(default=None, max_length=200)),
                ('personality_styles', models.CharField(default=None, max_length=200)),
                ('area_of_interests', models.CharField(default=None, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Fail',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('student_id', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('parental_status', models.CharField(max_length=200)),
                ('guardian', models.CharField(max_length=200)),
                ('intention', models.CharField(max_length=200)),
                ('romantic', models.CharField(max_length=200)),
                ('extra_curr', models.CharField(max_length=200)),
                ('alcohol_cons', models.CharField(max_length=200)),
                ('no_of_failures', models.CharField(max_length=200)),
                ('grade1', models.IntegerField()),
                ('grade2', models.IntegerField()),
                ('grade3', models.IntegerField()),
                ('result', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_styles', models.CharField(default=None, max_length=200)),
                ('personality_styles', models.CharField(default=None, max_length=200)),
                ('area_of_interests', models.CharField(default=None, max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.students')),
            ],
            options={
                'verbose_name_plural': 'Pass',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.fail')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.pass')),
            ],
            options={
                'verbose_name_plural': 'Match',
            },
        ),
        migrations.AddField(
            model_name='fail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.students'),
        ),
    ]
